config/routes.rb
Hv::Application.routes.draw do
  root to: 'static_pages#home'
  resources :clients do
    resources :homevisits, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :homevisits, only: [:index, :destroy]

end

app/models/bedday.rb
class Bedday < ActiveRecord::Base
  belongs_to :client, dependent: :destroy
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :homevisits, dependent: :destroy
  has_one :bedday
  validates :name, presence: true
  validates :titleXIX, presence: true, format: { with: /\d\d\d\d\d\d\d[A-Z]/  },
                       uniqueness: true
  before_save :create_bedday

  def hvs
    homevisits.all
  end

  def create_bedday
    client = build_bedday
    client.save
  end

  def days_gone
    days_gone = hvs.each.map do |hv|
      hv.return_date - hv.departure_date
    end
    (days_gone.inject(:+)).to_i
  end

  def current_beddays
    (bedday.remaining - days_gone).to_i
  end
end

app/models/homevisit.rb
class Homevisit < ActiveRecord::Base
  belongs_to :client
  validates :client_id, presence: true
  validates :departure_date, presence: true
  validates :return_date, presence: true

  def days
    (return_date - departure_date).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :find_client, except: [:new, :create, :index]
  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:success] = 'New Client Successfully Added'
      redirect_to @client
    else
      render 'new'
    end
  end

  def show
  end

  def index
    @clients = Client.order(:created_at)
  end

  def edit
  end

  def update
    @client.update(client_params)
    if @client.save
      flash[:success] = 'Client Successfully Updated'
      redirect_to @client
    else
      render 'edit'
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  private

  def client_params
    params.require(:client).permit(:name, :titleXIX)
  end

  def find_client
    @client = Client.find(params[:id])
  end
end

app/controllers/homevisits_controller.rb
class HomevisitsController < ApplicationController
  before_action :find_client, except: [:index, :destroy]
  before_action :find_homevisit, only: [:edit, :update, :destroy]

  def new
    @homevisit = @client.homevisits.new
  end

  def create
    @homevisit = @client.homevisits.new(homevisit_params)
    if @homevisit.save
      flash[:success] = 'New Homevisit Succesfully Added'
      redirect_to homevisits_path
    else
      render 'new'
    end
  end

  def index
    @clients = Client.order(:created_at)
  end

  def show
  end

  def edit
  end

  def update
    @homevisit.update(homevisit_params)
    if @homevisit.save
      flash[:success] = 'Homevisit Successfully Updated'
      redirect_to homevisits_path
    else
      render 'edit'
    end
  end

  def destroy
    @homevisit.destroy
    redirect_to homevisits_path
  end

  private

  def find_client
    @client = Client.find(params[:client_id])
  end

  def find_homevisit
    @homevisit = Homevisit.find(params[:id])
  end

  def homevisit_params
    params.require(:homevisit).permit(:departure_date, :return_date)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/homevisits_helper.rb
module HomevisitsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/destroy.html.erb
<h1>Clients#destroy</h1>
<p>Find me in app/views/clients/destroy.html.erb</p>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(@client) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :titleXIX %>
      <%= f.text_field :titleXIX, class: 'form-control' %>

      <%= f.submit 'Update Client', class: 'btn btn-sm btn-danger' %>
    <% end %>
  </div>
</div>

app/views/clients/index.html.erb
<h1 class='text-center'>Clients Index</h1>
<% @clients.each do |client| %>
  <ul class='list-unstyled'>
    <li>
      <%= link_to client.name, client_path(client) %> - <%= client.titleXIX %>
    </li>
  </ul>
<% end %>

app/views/clients/new.html.erb
<h1 class='text-center'>Add New Client</h1>
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for(@client) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :titleXIX %>
      <%= f.text_field :titleXIX, class: 'form-control' %>

      <div class='text-center hv'>
      <%= f.submit 'Create Client', class: 'btn btn-sm btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/clients/show.html.erb
<h3><%= @client.name %></h3>
<p><%= @client.titleXIX %></p>
<%= @client.days_gone %>
<p>Bed days remaining: <%= @client.current_beddays %>
<ul class='list-unstyled'>
  <li><%= link_to 'New Homevisit', new_client_homevisit_path(@client) %></li>
  <li><%= link_to 'Edit Client', edit_client_path %></li>
  <li><%= link_to 'Delete Client', client_path, method: :delete %></li>
</ul>

app/views/clients/update.html.erb
<h1>Clients#update</h1>
<p>Find me in app/views/clients/update.html.erb</p>

app/views/homevisits/edit.html.erb
<h1 class='text-center'>Edit Homevisit</h1>
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for([@client, @homevisit]) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class='text-center'><%= f.label :client, @client.name %></div>

      <%= f.label :Departure_date %>
      <%= f.date_field :departure_date, class: 'form-control' %>

      <%= f.label :Return_date %>
      <%= f.date_field :return_date, class: 'form-control' %>

      <div class='text-center hv'>
      <%= f.submit "Update Homevisit", class: 'btn btn-sm btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/homevisits/index.html.erb
<h1 class='text-center'>Homevisits Index</h1>
<ol><% @clients.each do |client| %>
  <li><strong><%= client.name %></strong></li>
    <% client.homevisits.all.each do |homevisit| %>
      <ul class='list-unstyled'><li><%= homevisit.departure_date %> - <%= homevisit.return_date %> Homevisit length: <%= homevisit.days %> <%= link_to 'Edit Homevisit', edit_client_homevisit_path(client, homevisit) %> <%= link_to 'Delete Homevisit', homevisit_path(homevisit), method: :delete %></li></ul>
    <% end %>
  <% end %></ol>

app/views/homevisits/new.html.erb
<h1 class='text-center'>New Homevisit</h1>
<div class='row'>
  <div class='col-md-6 col-md-offset-3'>
    <%= form_for([@client, @homevisit]) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class='text-center'><%= f.label :client, @client.name %></div>

      <%= f.label :Departure_date %>
      <%= f.date_field :departure_date, class: 'form-control' %>

      <%= f.label :Return_date %>
      <%= f.date_field :return_date, class: 'form-control' %>

      <div class='text-center hv'>
      <%= f.submit "Create Homevisit", class: 'btn btn-sm btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class='navbar navbar-fixed-top navbar-inverse'>
<div class='container'>
  <%= link_to 'Home', root_path, id: 'logo' %>
  <nav>
    <ul class='nav navbar-nav navbar-right'>
      <li><%= link_to 'New Client', new_client_path %></li>
      <li><%= link_to 'All Clients', clients_path %></li>
      <li><%= link_to 'All Homevisits', homevisits_path %></li>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hv</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class='container'>
    <% flash.each do |message_type, message| %>
      <div class='alert alert-<%=message_type %>'><%= message %></div>
    <% end %>
<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @client.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      The form contains <%= pluralize(@client.errors.count, 'error') %>.
    </div>
    <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class='center jumbotron'>
  <h1>Welcome to the Tanager Place Homevisit App</h1>

  <%= link_to 'Create a New Client now!', new_client_path, class: 'btn btn-lg btn-danger' %>
</div>

<%= link_to image_tag("tanager.jpg", alt: "Tanager Place"),
   'http://tanagerplace.org', id: "image" %>